config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      post :assign_to_me
    end
    resources :comments, only: [:create, :new]
  end

  resources :departments

  devise_for :users

  resources :users, only: [:index, :new, :edit, :update]

  resources :users do
    collection do
      post 'new', action: :create
    end

    member do
      put 'restore'
    end
  end

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid

  enum role: [:user, :manager, :admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :comments
  has_many :tickets, class_name: 'Ticket', foreign_key: 'assignee_id'

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :role, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, email: true

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:destroy, :edit, :update]
  before_action :set_destroyed_user, only: [:restore]

  # GET /users
  def index
    authorize User
    if @current_user.admin?
      @users = User.with_deleted
    else
      @users = User.all
    end
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # POST /user/new
  # POST /user/new.json
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: users_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /user/1/edit
  def edit
    authorize(@user)
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: users_path }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/restore
  # PATCH/PUT /users/1/restore.json
  def restore
    authorize(@user)

    respond_to do |format|
      if @user.restore
        format.html { redirect_to users_path, notice: 'User was successfully restored.' }
        format.json { render :show, status: :ok, location: users_path }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_destroyed_user
      @user = User.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :role)
    end

end

app/views/users/_edit_form.html.slim
= simple_form_for @user do |f|
  = f.input :username
  = f.input :email
  /* = f.input :password */
  /* = f.input :password_confirmation */
  = f.input :role, collection: User.roles.keys
  = f.button :submit

app/views/users/_form.html.slim
= simple_form_for @user, url: new_user_path do |f|
  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.input :role, collection: User.roles.keys
  = f.button :submit

app/views/users/edit.html.slim
h1 Editing User

== render 'edit_form'

= link_to 'Show', @user
'|
= link_to 'Back', :back

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th Role
      th Status
      th
      th
      th
  tbody
    - @users.each do |user|
      tr
        td = user.username
        td = user.email
        td = user.role
        td = user.deleted? ? 'Suspended' : 'Active'
        - if policy(user).edit?
          td = link_to 'Edit', edit_user_path(user)
        - if policy(user).destroy?
          td = link_to 'Suspend', user, data: {:confirm => 'Are you sure?'}, :method => :delete
        - if policy(user).restore?
          td = link_to 'Restore', restore_user_path(user), :method => :put

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
div.authform
  h3 New user
  == render 'form'

  = link_to 'Back', users_path