config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      post :assign_to_me
    end
    resources :comments, only: [:create, :new]
  end

  resources :departments

  devise_for :users

  resources :users, only: [:index, :new, :edit, :update]

  resources :users do
    collection do
      post 'new', action: :create
    end

    member do
      put 'restore'
    end
  end

  root 'home#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :tickets
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :description)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.slim
= simple_form_for(@department) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description, as: :text, input_html: { rows: 20 }

  .form-actions
    = f.button :submit

app/views/departments/edit.html.slim
h1 Editing department

== render 'form'

= link_to 'Show', @department
'|
= link_to 'Back', departments_path

app/views/departments/index.html.slim
h1 Listing departments

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @departments.each do |department|
      tr
        td = department.name
        td = link_to 'Show', department
        td = link_to 'Edit', edit_department_path(department)
        td = link_to 'Destroy', department, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Department', new_department_path

app/views/departments/new.html.slim
h1 New department

== render 'form'

= link_to 'Back', departments_path

app/views/departments/show.html.slim
p#notice = notice

h3 Department

p
  | Name: #{@department.name}
p
  | Description: #{@department.description}

= link_to 'Edit', edit_department_path(@department)
'|
= link_to 'Back', departments_path