config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      post :assign_to_me
    end
    resources :comments, only: [:create, :new]
  end

  resources :departments

  devise_for :users

  resources :users, only: [:index, :new, :edit, :update]

  resources :users do
    collection do
      post 'new', action: :create
    end

    member do
      put 'restore'
    end
  end

  root 'home#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include AASM
  extend FriendlyId

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  friendly_id :display_id

  has_many :comments, dependent: :destroy
  belongs_to :department, required: true
  belongs_to :assignee, -> { unscope(where: :deleted_at) }, class_name: 'User', foreign_key: 'assignee_id'

  validates :name, presence: true
  validates :email, presence: true, email: true
  validates :subject, presence: true
  validates :body, presence: true

  scope :assigned_to, ->(assignee_id) { where(assignee_id: assignee_id) }
  scope :unassigned, -> { where(assignee_id: nil, status: %w(new)) }
  scope :opened, -> { where(status: %w(new waited_for_customer on_hold)) }
  scope :on_holded, -> { where(status: %w(on_hold)) }
  scope :completed, -> { where(status: %w(completed canceled)) }

  aasm column: 'status' do
    state :new, initial: true # Waiting for Staff Response
    state :waited_for_customer
    state :on_hold
    state :canceled
    state :completed
  end

  after_create do |ticket|
    retry_count = 0

    begin
      ticket.update_attributes(display_id: Ticket.generate_display_id)
    rescue ActiveRecord::RecordNotUnique => e
      msg = "Unique display_id creation '#{ticket.display_id}' failed due to unique key constraint"
      retry_count += 1
      ticket.display_id = nil

      if retry_count <= 5
        logger.warn "#{msg}: retry attempt #{retry_count}."
        retry
      else
        logger.error "#{msg}: max retry attempts exceeded."
        raise e
      end
    end

  end

  # protected

  def self.generate_display_id
    # "ABC-4F-ABC-8D-ABC"
    "#{Array.new(3) { [*"A".."Z", *"0".."9"].sample }.join}-#{SecureRandom.hex(1).upcase}-#{Array.new(3) { [*"A".."Z", *"0".."9"].sample }.join}-#{SecureRandom.hex(1).upcase}-#{Array.new(3) { [*"A".."Z", *"0".."9"].sample }.join}"
  end
end

Ticket.import

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :assign_to_me]
  before_action :authenticate_user!, except: [:show, :new, :create]

  # GET /tickets
  # GET /tickets.json
  def index
    if params[:q].nil?
      @tickets = Ticket.all
    else
      @tickets = Ticket.search(params[:q]).records
    end

    authorize(@tickets)

    @tickets = case params[:status]
    when 'unassigned'
      @tickets.unassigned
    when 'opened'
      @tickets.opened
    when 'on_holded'
      @tickets.on_holded
    when 'closed'
      @tickets.completed
    else
      params[:status] = 'unassigned'
      @tickets.unassigned
    end

    @tickets = @tickets.paginate per_page: 2, page: params[:page]
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @users = User.all
    @comment = Comment.new
    @comments = @ticket.comments.paginate per_page: 2, page: params[:page]
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    authorize(@ticket)
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    authorize(@ticket)

    respond_to do |format|
      if @ticket.save
        TicketMailer.new_ticket(@ticket).deliver_later

        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    authorize(@ticket)
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign_to_me
    authorize(@ticket)
    @ticket.assignee = @current_user

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :show }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :subject, :body, :email, :assignee_id, :status, :department_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_comment_form.html.slim
= simple_form_for([@ticket, @comment]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :body, as: :text, input_html: { rows: 10 }

  .form-actions
    = f.button :submit

app/views/tickets/_form.html.slim
= simple_form_for(@ticket) do |f|
  = f.error_notification

  .form-inputs
    = f.association :department, include_blank: false
    = f.input :name
    = f.input :email
    = f.input :subject
    = f.input :body, as: :text, input_html: { rows: 20 }

  .form-actions
    = f.button :submit

app/views/tickets/_list.html.slim
= form_for tickets_path, method: :get do |f|
  p
    = f.label "Search for:"
    = text_field_tag :q, params[:q]
    = hidden_field_tag :status, params[:status]
    = submit_tag "Go", name: nil, class: 'button'

h2 Listing tickets
table
  thead
    tr
      th Email
      th Name
      th Subject
      th Body
      th
      th
      th

  tbody
    - @tickets.each do |ticket|
      tr
        td = ticket.email
        td = ticket.name
        td = ticket.subject
        td = ticket.body
        td = link_to 'Show', ticket
        - if policy(ticket).edit?
          td = link_to 'Edit', edit_ticket_path(ticket)
        - if policy(ticket).destroy?
          td = link_to 'Destroy', ticket, data: {:confirm => 'Are you sure?'}, :method => :delete

= will_paginate @tickets, renderer: FoundationPagination::Rails

app/views/tickets/edit.html.slim
h1 Editing ticket

== render 'form'

= link_to 'Show', @ticket
'|
= link_to 'Back', tickets_path

app/views/tickets/index.html.slim
/* ul class='tabs vertical' data-tab='' */
ul class='tabs'
  li class="tab-title #{'active' if params[:status] == 'unassigned' || params[:status].nil?}"
    = link_to 'New unassigned tickets', status: 'unassigned'
  li class="tab-title #{'active' if params[:status] == 'opened'}"
    = link_to 'Open Tickets', status: 'opened'
  li class="tab-title #{'active' if params[:status] == 'on_holded'}"
    = link_to 'On hold tickets', status: 'on_holded'
  li class="tab-title #{'active' if params[:status] == 'closed'}"
    = link_to 'Closed Tickets', status: 'closed'

div class='tabs-content'
  div class='content #{'active' if params[:status] == 'unassigned' || params[:status].nil?}'
    h1 New unassigned tickets
    == render 'list'
  div class='content #{'active' if params[:status] == 'opened'}'
    h1 Open tickets
    == render 'list'
  div class='content #{'active' if params[:status] == 'on_holded'}'
    h1 On hold tickets
    == render 'list'
  div class='content #{'active' if params[:status] == 'closed'}'
    h1 Closed tickets
    == render 'list'

hr

= button_to 'New Ticket', new_ticket_path, class: 'button', method: :get

app/views/tickets/new.html.slim
h1 New ticket

== render 'form'

= link_to 'Back', :back

app/views/tickets/show.html.slim
/* p#notice = notice */

= link_to '<< Back', :back

- if policy(@ticket).edit?
  = button_to 'Assign to me', assign_to_me_ticket_path, class: 'button tiny'

  div class='large-4'
    = simple_form_for @ticket do |f|
      = f.input :assignee_id, collection: @users, label_method: :username, value_method: :id, label: 'Select user to assign', include_blank: false
      = f.button :submit, 'Assign', class: 'button tiny'
  div class='large-4'
    = simple_form_for @ticket do |f|
      = f.input :status, collection: Ticket.aasm.states, label_method: :name, value_method: :name, label: 'Select status', include_blank: false
      = f.button :submit, 'Change status', class: 'button tiny'

h3 = @ticket.subject

span.label
  = @ticket.status

p
  | #{@ticket.name} openned this issue on #{@ticket.created_at}

p
  - if @ticket.assignee
    | Assigned to #{@ticket.assignee.username}
  - else
    | Not assigned

p
  | Department: #{@ticket.department.try(:name)}

div.panel
  = @ticket.body

- if policy(@ticket).edit?
  = button_to 'Edit', edit_ticket_path(@ticket), method: :get, class: 'button small'
hr

div
  div[class='large-8 columns']
    h3 Comments (#{@comments.count})

    - @comments.each do |comment|
      p
        | #{comment.try(:user).try(:username) || 'Customer'} commented on #{comment.created_at}

      div.panel
        = comment.body

    = will_paginate @comments, renderer: FoundationPagination::Rails
  div[class='large-4 columns']
    - if policy(@comments).new?
      h3 New comment
      == render '/tickets/comment_form'