config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      post :assign_to_me
    end
    resources :comments, only: [:create, :new]
  end

  resources :departments

  devise_for :users

  resources :users, only: [:index, :new, :edit, :update]

  resources :users do
    collection do
      post 'new', action: :create
    end

    member do
      put 'restore'
    end
  end

  root 'home#index'

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a[href="#"]
        Menu
  .top-bar-section
    ul
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
/* add navigation links to this file */
- if user_signed_in?
  li
    = link_to 'Sign out', destroy_user_session_path, data: {:confirm => 'Are you sure?'}, :method => :delete
- else
  li
    = link_to 'Sign in', new_user_session_path

- if policy(:ticket).index?
  li
    = link_to 'Tickets', tickets_path

- if policy(:department).index?
  li
    = link_to 'Departments', departments_path

- if policy(:user).index?
  li
    = link_to 'Users', users_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Support Issue Tracking'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Support Issue Tracking'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main" class="small-12 columns"]
      == render 'layouts/messages'
      == yield
      /* == console */